version: '3.7'
services:
  backend:
    image: antoniopapa1991/influencer-backend
    environment:
      DB_HOST: db
      DB_DATABASE: influencer
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - app
  db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: influencer
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - app

networks:
  app:
